#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo "Running tests..."
pnpm exec jest --silent --passWithNoTests
TEST_STATUS=$?
if [ $TEST_STATUS -ne 0 ]; then
  echo "Tests failed. Aborting commit."
  exit $TEST_STATUS
fi

npx lint-staged
